# FROM python:3.11-slim AS builder
FROM public.ecr.aws/lambda/python:3.12 AS builder
WORKDIR /app
COPY requirements.txt /app/
# RUN apt-get update && apt-get install -y build-essential libpq-dev libsndfile1 ffmpeg && rm -rf /var/lib/apt/lists/*
RUN dnf install -y gcc gcc-c++ make postgresql-devel && dnf clean all
RUN python -m venv /opt/venv \
	&& /opt/venv/bin/python -m pip install --upgrade pip setuptools wheel \
	&& /opt/venv/bin/pip install --no-cache-dir -r requirements.txt

# FROM python:3.11-slim
FROM public.ecr.aws/lambda/python:3.12
WORKDIR /app
COPY --from=builder /opt/venv /opt/venv
COPY app ./app
COPY docs ./docs
ENV PATH=/opt/venv/bin:$PATH
ENV PYTHONPATH=/app:$PYTHONPATH

# CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
CMD ["app.main.handler"]